default_settings: null
behaviors:
  NoPSModel:
    trainer_type: sac
    hyperparameters:
      learning_rate: 1e-5
      learning_rate_schedule: constant
      batch_size: 128
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 20.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 100000
  
environment_parameters: 
  density:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.75
      max_value: 1.75

  fluid_rest_distance:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.10
      max_value: 0.15

  tolerance:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.02
      max_value: 0.02

  
  adhesion:
    curriculum:
      - name: AdhesionFirstLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.25
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.0
            max_value: 0.005
      - name: AdhesionSecondLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.50
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.005
            max_value: 0.010
      - name: AdhesionThirdLesson
        value:
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.010
            max_value: 0.025

  cohesion:
    curriculum:
      - name: CohesionFirstLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.25
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.0
            max_value: 0.005
      - name: CohesionSecondLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.50
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.005
            max_value: 0.01
      - name: CohesionThirdLesson
        value:
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.01
            max_value: 0.2

  surfaceTension:
    curriculum:
      - name: SurfaceTensionFirstLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.25
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.0
            max_value: 0.005
      - name: SurfaceTensionSecondLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.50
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.005
            max_value: 0.01
      - name: SurfaceTensionThirdLesson
        value:
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.01
            max_value: 0.02
  
  viscosity:
    curriculum:
      - name: ViscosityFirstLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.25
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 0.0
            max_value: 50.0
      - name: ViscositySecondLesson
        completion_criteria:
          measure: progress
          behavior: NoPSModel
          signal_smoothing: true
          min_lesson_threshold: 100
          threshold: 0.50
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 50.0
            max_value: 100.0
      - name: ViscosityThirdLesson
        value: 
          sampler_type: uniform
          sampler_parameters: 
            min_value: 100.0
            max_value: 200.0