---
lmt_msgs/Object[] objects
---
uint8 PROGRESS_STARTED = 0
uint8 PROGRESS_CLOUD_FILTERED = 14
uint8 PROGRESS_TABLE_REMOVED = 29
uint8 PROGRESS_OBJECT_CLOUD_CREATED = 43
uint8 PROGRESS_OBJECT_CLUSTERS_CREATED = 57
uint8 PROGRESS_KEYPOINTS_EXTRACTED = 71
uint8 PROGRESS_DESCRIPTORS_CREATED = 86
uint8 PROGRESS_OBJECTS_MATCHED = 100
uint8 progress
