#!/bin/bash

sudo apt install -y ros-melodic-control-toolbox 
sudo apt install -y ros-melodic-moveit-core 
sudo apt install -y ros-melodic-costmap-2d 
sudo apt install -y ros-melodic-move-base 
sudo apt install -y ros-melodic-jsk-recognition 
sudo apt install -y ros-melodic-controller-manager 
sudo apt install -y ros-melodic-gazebo-ros* 
sudo apt install -y ros-melodic-hector* 
sudo apt install -y ros-melodic-rviz-imu-plugin 
sudo apt install -y ros-melodic-robot-pose-ekf 
sudo apt install -y ros-melodic-robot-localization 
sudo apt install -y ros-melodic-yocs-cmd-vel-mux 
sudo apt install -y ros-melodic-joint-* 
sudo apt install -y ros-melodic-grasp-planning-graspit-ros 
sudo apt install -y ros-melodic-jaco-graspit-sample 
sudo apt install -y ros-melodic-graspit-tools 
sudo apt install -y libsuitesparse-dev 
sudo apt install -y ros-melodic-costmap-converter 
sudo apt install -y ros-melodic-libg2o 
sudo apt install -y ros-melodic-eigen-conversions 
sudo apt install -y ros-melodic-eigen-stl-containers 
sudo apt install -y libeigen3-dev 
sudo apt install -y ros-melodic-trac-ik 
sudo apt install -y ros-melodic-moveit 
sudo apt install -y ros-melodic-ros-controllers 
sudo apt install -y ros-melodic-map-server 
sudo apt install -y ros-melodic-amcl 
sudo apt install -y ros-melodic-global-planner
