station_WIFI_ip: 10.66.171.120
station_camera_stream: true
station_lidar_stream: true
station_status_stream: true
print_debug: false
station_5G_ip: 10.162.148.135
station_camera_resize_ratio: 0.3
station_mode: WIFI
station_camera_frame_skip_ratio: 5
station_ip: 10.66.171.182
station_camera_jpeg_compression_ratio: 50