default_settings: null
behaviors:
  NoPSModel:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 10240
      learning_rate: 1e-5
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.05
      lambd: 0.92
      num_epoch: 5
    network_settings:
      use_recurrent: true
      normalize: false
      hidden_units: 512
      num_layers: 3
      sequence_length: 64
      memory_size: 256
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 100000
  
environment_parameters: 
  density:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.75
      max_value: 1.75

  fluid_rest_distance:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.10
      max_value: 0.15
      
  tolerance:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.020
      max_value: 0.020

  adhesion:
    sampler_type: uniform
    sampler_parameters: 
      min_value: 0.0
      max_value: 0.025

  cohesion:
    sampler_type: uniform
    sampler_parameters: 
      min_value: 0.0
      max_value: 0.2

  surfaceTension:
    sampler_type: uniform
    sampler_parameters: 
      min_value: 0.0
      max_value: 0.02
  
  viscosity:
    sampler_type: uniform
    sampler_parameters: 
      min_value: 0.0
      max_value: 200.0